[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.3.6"
  JEKYLL_ENV = "production"

[context.production]
  environment = { JEKYLL_ENV = "production" }

[context.deploy-preview]
  command = "bundle install && bundle exec jekyll build --future"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
